kind: pipeline
type: docker
name: integration

steps:
  - name: code_analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - dotnet sonarscanner begin
      - /k:"easv-devops_Currency_Converter_WebApp_AY7wP4O_EVvRW2O60Eyq"
      - /d:sonar.host.url="http://sonar.setgo.dk:9000"
      - /d:sonar.token="$SONARSECRET"
      - /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

---

kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:
  - name: publish api
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: api/Dockerfile
      repo: doina1992/cd-converter-api
      tags:
        - staging

  - name: publish web
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername 
      password:
        from_secret: DockerPassword
      context: .     
      dockerfile: frontend/Dockerfile
      repo: doina1992/cd-conversion-web
      tags:
        - staging
        
        
  - name: trigger update
    image: curlimages/curl
    commands:
      - "curl --fail -X GET 'http://144.91.75.24:8080/v1/update' -H 'Authorization: Bearer mytoken'" # Replace with your Termius IP address and token
      - sleep 10
    depends_on:
      - publish api
      - publish web


  - name: update database
    image: flyway/flyway
    commands:
        - flyway migrate
          -url=jdbc:mariadb://144.91.75.24:5432/cc
          -user=user
          -password=password
          -locations=filesystem:./db/sql
    depends_on:
        - trigger update



  - name: performance tests
    image: grafana/k6
    commands:
        - k6 run tests/spike-conv.js
        - k6 run tests/history-test.js
    depends_on:
        - update database



  - name: end-to-end tests
    image: testcafe/testcafe
    commands:
        - testcafe chromium:headless tests/e2e.js
        - testcafe chromium:headless tests/e2e.conv.js
    depends_on:
        - update database