
version: '3.3'

services:
  postgres-database:
    image: postgres:latest
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD= PASSWORD
      - POSTGRES_USER= qzwptyqr
      - POSTGRES_DB= DATABASE
      
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    environment:
      - FLYWAY_BASELINE_ON_MIGRATE=true
  
    depends_on:
      - postgres-database


